### ISSUE TITLE
Crash when running channelz channels

### ISSUE THREAD

**Issue by veblush** [grpc-ecosystem/grpcdebug#16]
Version: https://github.com/grpc-ecosystem/grpcdebug/releases/tag/v1.0.4

```
$ grpcdebug localhost:50051 channelz channels
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xb977fc]

goroutine 1 [running]:
github.com/grpc-ecosystem/grpcdebug/cmd.channelzChannelsCommandRunWithError(0x1fd33c0?, {0x20177a0?, 0x0?, 0x0?})
        /home/veblush/go/pkg/mod/github.com/grpc-ecosystem/grpcdebug@v1.0.4/cmd/channelz.go:118 +0x1bc
github.com/spf13/cobra.(*Command).execute(0x1fd33c0, {0x20177a0, 0x0, 0x0})
        /home/veblush/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x1fd4b60)
        /home/veblush/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x39d
github.com/spf13/cobra.(*Command).Execute(...)
        /home/veblush/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/grpc-ecosystem/grpcdebug/cmd.Execute()
        /home/veblush/go/pkg/mod/github.com/grpc-ecosystem/grpcdebug@v1.0.4/cmd/root.go:107 +0xde
main.main()
        /home/veblush/go/pkg/mod/github.com/grpc-ecosystem/grpcdebug@v1.0.4/main.go:163 +0x17
```

**Comment by veblush** [comment]
@dfawley Doug, would you help me fix this?

**Comment by dfawley** [comment]
I can help you debug this whenever you're available.  But I will say the code on this line:

https://github.com/grpc-ecosystem/grpcdebug/blob/4b23165d4c3aeac3f167b7ca0a78f0af863fc529/cmd/channelz.go#L118

(where the nil pointer deref is reported) could be improved.  It's accessing protos and sub-messages, and would be better if it used `Get<Field>().Get<Field>()`, which avoids the panic in case there are nil parent messages.
